'use client';
import { FormEvent,useState } from 'react'; import { useRouter } from 'next/navigation'; import Link from 'next/link'; import { LockKeyhole } from 'lucide-react';
import { Header } from '@/components/Header'; import { Footer } from '@/components/Footer'; import { useCart } from '@/context/CartContext'; import { api } from '@/lib/api'; import type { Order } from '@/lib/types';
export default function CheckoutPage(){
 const {items,subtotal,clear}=useCart(); const router=useRouter(); const [form,setForm]=useState({customerName:'',email:'',phone:'',address:'',city:'Amman',notes:''});const [error,setError]=useState('');const [sending,setSending]=useState(false);const delivery=subtotal>=100||subtotal===0?0:5;
 async function submit(e:FormEvent){e.preventDefault();if(!items.length)return;setSending(true);setError('');try{const order=await api<Order>('/orders',{method:'POST',body:JSON.stringify({...form,items:items.map(i=>({productId:i.product._id,quantity:i.quantity,size:i.size,color:i.color}))})});clear();sessionStorage.setItem('wear_it_last_order',JSON.stringify({number:order.orderNumber,total:order.total}));router.push('/order-success')}catch(e){setError(e instanceof Error?e.message:'Could not place order')}finally{setSending(false)}}
 if(!items.length)return <><Header/><main className="stateView"><h3>Nothing to check out</h3><p>Your bag is empty.</p><Link href="/shop" className="button">Go to shop</Link></main><Footer/></>;
 return <><Header/><main className="checkoutPage"><div className="container"><h1 className="pageTitle">Checkout.</h1><div className="checkoutLayout"><form className="checkoutForm" onSubmit={submit}><h3>Delivery details</h3><div className="formGrid">{[['customerName','Full name','Hakam Qadi'],['email','Email','you@example.com'],['phone','Phone','07XXXXXXXX'],['city','City','Amman'],['address','Delivery address','Street, building, floor']].map(([name,label,placeholder],i)=><label className={`formField ${name==='address'?'full':''}`} key={name}><span>{label}</span><input required className="input" type={name==='email'?'email':'text'} minLength={name==='address'?5:2} value={form[name as keyof typeof form]} placeholder={placeholder} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>)}<label className="formField full"><span>Order notes <em className="muted">(optional)</em></span><textarea className="textarea" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Delivery instructions, preferred contact method…"/></label></div>{error&&<p className="fieldError">{error}</p>}<div className="freeDelivery"><LockKeyhole size={13} style={{verticalAlign:'middle'}}/> Demo checkout uses cash on delivery; no card data is collected.</div><button className="button" disabled={sending} type="submit">{sending?'Placing order…':'Place order'}</button></form><aside className="summaryCard"><h3>Summary</h3>{items.map(i=><div className="summaryRow" key={`${i.product._id}-${i.size}-${i.color}`}><span>{i.quantity} × {i.product.name}</span><strong>${(i.product.price*i.quantity).toFixed(2)}</strong></div>)}<div className="summaryRow"><span>Delivery</span><strong>{delivery?'$5.00':'Free'}</strong></div><div className="summaryRow total"><span>Total</span><span>${(subtotal+delivery).toFixed(2)}</span></div></aside></div></div></main><Footer/></>;
}
