'use client';
import Link from 'next/link';
import { usePathname, useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { LogOut, Menu, Shirt, Sparkles, X } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { useI18n, type TranslationKey } from '@/context/I18nContext';
import { api } from '@/lib/api'; import { text } from '@/lib/localise'; import type { SiteContent } from '@/lib/types'; import { LanguageSwitch } from './LanguageSwitch';
type MemberLink=readonly[string,TranslationKey|null]; const MEMBER_LINKS:ReadonlyArray<MemberLink>=[['/closet','nav.closet'],['/studio','nav.studio'],['/looks','nav.looks'],['/photos','nav.photos'],['/billing',null]];
export function Header(){const{user,ready,logout}=useAuth(),{t,locale}=useI18n(),router=useRouter(),path=usePathname();const[open,setOpen]=useState(false),[content,setContent]=useState<Pick<SiteContent,'brandName'|'announcement'>|null>(null);useEffect(()=>{api<SiteContent>('/content').then(v=>setContent({brandName:v.brandName,announcement:v.announcement})).catch(()=>{})},[]);const brand=text(content?.brandName,locale,'Wear It'),announcement=text(content?.announcement,locale,t('home.announcementDefault'));return <>{announcement&&<div className="announcement">{announcement}</div>}<header className="siteHeader"><Link href={user?'/closet':'/'} className="brand"><span className="brandDot"><Shirt size={17}/></span>{brand}</Link><nav className={`navLinks ${open?'navOpen':''}`}>{user?MEMBER_LINKS.map(([href,key])=><Link key={href} href={href} className={path===href?'active':''} onClick={()=>setOpen(false)}>{key?t(key):locale==='ar'?'الخطة':'Plan'}</Link>):<><Link href="/#how-it-works">{t('nav.howItWorks')}</Link><Link href="/login">{t('common.signIn')}</Link></>}<span className="navLanguage"><LanguageSwitch/></span></nav><div className="headerActions"><span className="desktopLanguage"><LanguageSwitch compact/></span>{!ready?null:user?<><Link className="primaryPill" href="/studio"><Sparkles size={16}/><span className="pillLabel">{t('nav.createLook')}</span></Link><button className="iconButton" aria-label={t('common.signOut')} onClick={()=>{logout();router.replace('/')}}><LogOut size={18}/></button></>:<Link className="primaryPill" href="/register"><span className="pillLabel">{t('nav.getStarted')}</span></Link>}<button className="iconButton mobileMenu" aria-label={t('nav.toggleMenu')} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button></div></header></>}
