'use client';
import Image from 'next/image'; import Link from 'next/link'; import { Camera, LockKeyhole, RotateCcw, ShoppingBag, Sparkles, Upload } from 'lucide-react'; import { useParams } from 'next/navigation'; import { ChangeEvent,useEffect,useState } from 'react';
import { Header } from '@/components/Header'; import { Footer } from '@/components/Footer'; import { LoadingState } from '@/components/StateViews'; import { api,mediaUrl } from '@/lib/api'; import type { Product } from '@/lib/types';
export default function TryOnPage(){
 const {slug}=useParams<{slug:string}>(); const [product,setProduct]=useState<Product|null>(null); const [photo,setPhoto]=useState(''); const [scale,setScale]=useState(52); const [x,setX]=useState(50); const [y,setY]=useState(42);
 useEffect(()=>{api<Product>(`/products/${slug}`).then(setProduct).catch(()=>{});return()=>{if(photo.startsWith('blob:'))URL.revokeObjectURL(photo)}},[slug]);
 function pick(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(photo.startsWith('blob:'))URL.revokeObjectURL(photo);setPhoto(URL.createObjectURL(f));}
 if(!product)return <><Header/><LoadingState label="Opening fitting room"/><Footer/></>;
 return <><Header/><main className="tryOnPage"><div className="container"><div className="tryOnHeaderBlock"><span className="eyebrow"><Sparkles size={12} style={{verticalAlign:'middle'}}/> Virtual fitting room</span><h1>See the silhouette on you.</h1><p>For the best result, use a clear front-facing photo with your upper body visible and adjust the garment until it feels aligned.</p></div><div className="tryWorkspace"><div className="tryCanvas">{photo?<><Image src={photo} alt="Your uploaded try-on preview" fill unoptimized className="personPhoto"/><div className="garmentOverlay" style={{width:`${scale}%`,left:`${x}%`,top:`${y}%`}}><div style={{position:'relative',aspectRatio:'1/1.05',width:'100%'}}><Image src={mediaUrl(product.tryOnOverlayUrl)} alt={`${product.name} overlay`} fill unoptimized style={{objectFit:'contain'}}/></div></div></>:<div className="uploadEmpty"><div className="uploadCircle"><Camera size={28}/></div><h3>Add a photo of yourself</h3><p>Choose a front-facing JPG, PNG or WEBP image from your device.</p><label className="button"><Upload size={17}/>Choose photo<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={pick}/></label></div>}</div><aside className="tryControls"><div className="tryProductMini"><Image src={mediaUrl(product.images[0])} width={54} height={66} unoptimized alt={product.name}/><div><strong>{product.name}</strong><small>${product.price.toFixed(2)}</small></div></div><h3>Adjust the preview</h3><p>The preview is a visual guide, not a body measurement or size guarantee.</p>{[['Scale',scale,setScale,30,85],['Horizontal',x,setX,20,80],['Vertical',y,setY,20,75]].map(([label,value,setter,min,max])=><label className="rangeField" key={String(label)}><span><b>{label as string}</b><em>{value as number}%</em></span><input type="range" min={min as number} max={max as number} value={value as number} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))}/></label>)}<button className="button secondary" style={{width:'100%'}} onClick={()=>{setScale(52);setX(50);setY(42)}}><RotateCcw size={16}/>Reset position</button>{photo&&<label className="button secondary" style={{width:'100%',marginTop:8}}><Upload size={16}/>Change photo<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={pick}/></label>}<Link href={`/product/${product.slug}`} className="button accent" style={{width:'100%',marginTop:8}}><ShoppingBag size={16}/>Choose size & add</Link><div className="tryPrivacy"><LockKeyhole size={16}/><span>Your photo is processed only in this browser preview and is not uploaded to the Wear It API.</span></div></aside></div></div></main><Footer/></>;
}
